Update the-obvious-hq.md...
obvious/playbook pull request #7
Opened 2019-09-16 11:27 UTC by tanvibhakta

...to reflect location and transportation options

2019-09-16 11:29 UTC, tanvibhakta commented on employee-handbook/starting-at-obvious/the-obvious-hq.md
> -The office is officially open Monday to Friday. We encourage you to take weekends off from work, and use the space for anything fun—screen a movie, invite friends over to play board games or party. I
We should add a separate, more detailed section on using the space over the weekend, with guest policies and links to POSH policy, etc. I'll work on this in a bit.

2019-09-16 11:29 UTC, tanvibhakta commented on employee-handbook/starting-at-obvious/the-obvious-hq.md
> +
I want this section to be about the various parts of the office and what they are likely to be used for.

2019-09-16 11:35 UTC, tanvibhakta commented
I also definitely think this one long page would be much better served by creating many shorter pages, and we can work on that as well.

2019-09-18 07:19 UTC, pratul requested changes

2019-09-18 07:19 UTC, pratul commented on employee-handbook/starting-at-obvious/the-obvious-hq.md
> +WIP
```suggestion
WIP: mention the various parts of the office and what they are likely/meant to be used for.
```

2019-09-18 09:29 UTC, merged